<a href="https://colab.research.google.com/github/Pranavee78/impulse/blob/main/task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()


In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

aynahd_eeg_signals_impulse_path = kagglehub.dataset_download('aynahd/eeg-signals-impulse')
aynahd_val_data_path = kagglehub.dataset_download('aynahd/val-data')

print('Data source import complete.')


In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_511.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_566.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_209.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_94.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_366.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_636.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_723.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_588.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_549.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_599.npy
/kaggle/input/eeg-signals-impulse/test_data-20250117T161526Z-001/test_data/test_56.npy
/kaggle/input/eeg-signals-impulse/

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

# Path to the dataset folders
data_path = '/kaggle/input/eeg-signals-impulse/train_data-20250117T173905Z-001/train_data'
folders = ['Normal', 'Complex_Partial_Seizures', 'Electrographic_Seizures', 'Video_detected_Seizures_with_no_visual_change_over_EEG']

In [ ]:
def load_eeg_data(folder):
    # Create the full folder path
    folder_path = os.path.join(data_path, folder)
    print(f"Checking folder path: {folder_path}")

    # Check if the folder exists
    if not os.path.exists(folder_path):
        print(f"Folder {folder_path} does not exist.")
        return None

    # List all files in the folder
    files = os.listdir(folder_path)
    print(f"Files in {folder}: {files}")

    # Check if the folder is empty
    if not files:
        print(f"Folder {folder_path} is empty.")
        return None

    # Get the first file and check if it's a .npy file
    file_path = os.path.join(folder_path, files[0])
    if not file_path.endswith('.npy'):
        print(f"Skipping {file_path} as it is not a .npy file.")
        return None

    # Attempt to load the .npy file
    print(f"Loading data from: {file_path}")
    try:
        data = np.load(file_path)
        print(f"Loaded data shape: {data.shape}")
        return data
    except Exception as e:
        print(f"Error loading data from {file_path}: {e}")
        return None

# Iterate through the folders and load one file from each
for folder in folders:
    print(f"Processing folder: {folder}")
    data = load_eeg_data(folder)
    if data is not None:
        print(data)  # Print the data (or process it further)
    else:
        print(f"No data loaded from folder: {folder}")

Processing folder: Normal
Checking folder path: /kaggle/input/eeg-signals-impulse/train_data-20250117T173905Z-001/train_data/Normal
Files in Normal: ['4548.npy', '5788.npy', '3709.npy', '6104.npy', '4684.npy', '2765.npy', '5197.npy', '5590.npy', '5669.npy', '331.npy', '4299.npy', '2434.npy', '4769.npy', '6082.npy', '4960.npy', '2424.npy', '4621.npy', '4706.npy', '6862.npy', '1200.npy', '3155.npy', '3844.npy', '719.npy', '4791.npy', '6773.npy', '5575.npy', '6254.npy', '4792.npy', '1191.npy', '461.npy', '4155.npy', '5980.npy', '3006.npy', '2083.npy', '1778.npy', '1702.npy', '5175.npy', '2528.npy', '4093.npy', '3996.npy', '2803.npy', '4136.npy', '6222.npy', '3992.npy', '2980.npy', '6365.npy', '5952.npy', '1965.npy', '6002.npy', '4705.npy', '464.npy', '2942.npy', '1479.npy', '4780.npy', '6699.npy', '4184.npy', '122.npy', '2785.npy', '3914.npy', '4495.npy', '1175.npy', '6549.npy', '407.npy', '2114.npy', '3799.npy', '5614.npy', '4186.npy', '5167.npy', '3302.npy', '6001.npy', '2704.npy', '216

In [ ]:
import os
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from scipy.fft import fft

In [ ]:
#mapped class labels based on folder names.

train_data_path = "/kaggle/input/eeg-signals-impulse/train_data-20250117T173905Z-001/train_data"
val_data_path = "/kaggle/input/val-data//kaggle/input/val-data/validation_data/"

class_labels = {
    "Complex_Partial_Seizures": 0,
    "Electrographic_Seizures": 1,
    "Normal": 2,
    "Video_detected_Seizures_with_no_visual_change_over_EEG": 3
}

In [ ]:
x_train = []
y_train = []

for class_name, label in class_labels.items():
    class_folder = os.path.join(train_data_path, class_name)
    for file_name in os.listdir(class_folder):
        file_path = os.path.join(class_folder, file_name)
        if file_name.endswith('.npy'):
            data = np.load(file_path)
            x_train.append(data)
            y_train.append(label)

In [ ]:
x_val = []
y_val = []

for class_name, label in class_labels.items():
    class_folder = os.path.join(val_data_path, class_name)
    for file_name in os.listdir(class_folder):
        file_path = os.path.join(class_folder, file_name)
        if file_name.endswith('.npy'):
            data = np.load(file_path)
            x_val.append(data)
            y_val.append(label)

In [ ]:
x_train = np.array(x_train)
y_train = np.array(y_train)

print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")


x_train shape: (5608, 19, 500)
y_train shape: (5608,)


In [ ]:
#
import numpy as np

def generate_features(signals, n):
    """
    Generate comprehensive features for a list of EEG signals.

    Parameters:
        signals (list of np.ndarray): List of 1D arrays representing EEG signals.
        n (int): Number of Fourier coefficients to extract.

    Returns:
        np.ndarray: 2D array where each row corresponds to the feature set of a signal.
    """
    def fourier_features(signal, n):
        """Compute the first n Fourier coefficients (magnitude)."""
        fft = np.fft.fft(signal)
        return np.abs(fft[:n])

    def zero_crossing_rate(signal):
        """Calculate the zero-crossing rate of a signal."""
        return ((signal[:-1] * signal[1:]) < 0).sum() / len(signal)

    def statistical_features(signal):
        """Compute statistical features like mean, variance, skewness, and kurtosis."""
        mean = np.mean(signal)
        std = np.std(signal)
        var = np.var(signal)
        skewness = np.mean((signal - mean) ** 3) / (std ** 3 + 1e-8)  # Avoid division by zero
        kurtosis = np.mean((signal - mean) ** 4) / (std ** 4 + 1e-8)
        return np.array([mean, std, var, skewness, kurtosis])

    def energy_and_rms(signal):
        """Compute signal energy and root mean square."""
        energy = np.sum(signal ** 2)
        rms = np.sqrt(np.mean(signal ** 2))
        return np.array([energy, rms])

    features = []
    for signal in signals:
        if len(signal) == 0:
            raise ValueError("Empty signal encountered.")

        # Frequency-domain features
        ff = fourier_features(signal, n)

        # Time-domain features
        zcr = zero_crossing_rate(signal)
        stats = statistical_features(signal)
        energy_rms = energy_and_rms(signal)

        # Combine all features
        combined_features = np.concatenate((ff, [zcr], stats, energy_rms))
        features.append(combined_features)

    # Convert list of features to a 2D NumPy array
    feature_array = np.array(features)

    # Normalize features (optional but recommended for machine learning models)
    normalized_features = (feature_array - np.mean(feature_array, axis=0)) / (np.std(feature_array, axis=0) + 1e-8)

    return normalized_features


features = generate_features(x_train, n)
features_val = generate_features(x_val, n)


print(f"Training features shape: {features.shape}")
print(f"Validation features shape: {features_val.shape}")

if features.shape[1] != features_val.shape[1]:
    min_features = min(features.shape[1], features_val.shape[1])
    features = features[:, :min_features]
    features_val = features_val[:, :min_features]

scaler = StandardScaler()
features = scaler.fit_transform(features)
features_val = scaler.transform(features_val)


svm_model = SVC(kernel='rbf')
svm_model.fit(features, y_train)

y_pred = svm_model.predict(features_val)

Training features shape: (939, 17)
Validation features shape: (235, 17)
Accuracy: 0.548936170212766

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.34      0.43        87
           1       0.00      0.00      0.00        26
           2       0.55      0.85      0.66       117
           3       0.00      0.00      0.00         5

    accuracy                           0.55       235
   macro avg       0.28      0.30      0.27       235
weighted avg       0.48      0.55      0.49       235



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score, balanced_accuracy_score
from sklearn.preprocessing import label_binarize

# Predict on validation set
y_pred = svm_model.predict(features_val)

print("Accuracy:", accuracy_score(y_val, y_pred))
balanced_acc = balanced_accuracy_score(y_val, y_pred)
print(f"\nBalanced Accuracy: {balanced_acc:.4f}")

# ROC AUC (for multi-class classification, binarize labels)
y_val_bin = label_binarize(y_val, classes=np.unique(y_val))
y_pred_bin = label_binarize(y_pred, classes=np.unique(y_val))

roc_auc = roc_auc_score(y_val_bin, y_pred_bin, average='macro', multi_class='ovr')  # one-vs-rest
print(f"\nROC AUC Score: {roc_auc:.4f}")


Accuracy: 0.548936170212766

Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.34      0.43        87
           1       1.00      0.00      0.00        26
           2       0.55      0.85      0.66       117
           3       1.00      0.00      0.00         5

    accuracy                           0.55       235
   macro avg       0.78      0.30      0.27       235
weighted avg       0.61      0.55      0.49       235


Confusion Matrix:
[[30  0 57  0]
 [ 3  0 23  0]
 [18  0 99  0]
 [ 3  0  2  0]]

Balanced Accuracy: 0.2977

ROC AUC Score: 0.5417
